gr1.gotoAndPlay("loop");
gr2.gotoAndPlay("loop");
gr3.gotoAndPlay("loop");
gr4.gotoAndPlay("loop");
play();
car.deuren.d1.gotoAndPlay("open");
car.deuren.d2.gotoAndPlay("open");
car.deuren.d3.gotoAndPlay("open");
car.deuren.d4.gotoAndPlay("open");
wellDone = true;
